services:
  vue:
    image: node:21-bookworm-slim
    container_name: vue
    volumes:
      - ./vuetify-project:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "4000:4000"
  
  back:
    image: node:21-bookworm-slim
    container_name: back
    volumes:
      - ./node:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && node index.js"
    ports:
      - "3589:3589"
    links:
      - vue
  
  db:
    image: mysql:8.2.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: persones
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      # Per guardar les dades de forma persistent
      - ./mysql/mysql_data:/var/lib/mysql
      # Per crear algunes taules al primer inici
      # - ./mysql/dades.sql:/docker-entrypoint-initdb.d/dades.sql
  
  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
