services:
  node-app:
    image: node:21-alpine3.18
    volumes:
      - ./vuetify-project:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "4000:4000"
  