services:
  vue:
    image: node:21-bookworm-slim
    container_name: vue
    volumes:
      - ./vuetify-project:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "4000:4000"
  back:
    image: node:21-bookworm-slim
    container_name: back
    volumes:
      - ./node:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && node index.js"
    ports:
      - "3589:3589"
    links:
      - vue
  