name: Preparant per producció
run-name: ${{ github.actor }} està pujant l'aplicació a PROD  🚀
on: [push]
jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install npm dependencies for vuetify
        working-directory: ./vuetify-project
        run: npm install
      
      - name: Run build task
        working-directory: ./vuetify-project
        run: npm run build --if-present

      - name: Pujant vue
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: vuetify-project/dist/
          remote_path: ${{ secrets.REMOTE_TARGET }}vuetify
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}  

      - name: Pujant node  
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: node/
          remote_path: ${{ secrets.REMOTE_TARGET }}node
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}  

      - name: Pujant laravel  
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: laravel/
          remote_path: ${{ secrets.REMOTE_TARGET }}laravel
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }} 

     
      - name: Npm install i composer install a prod
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: | 
            ls && cd ${{ secrets.REMOTE_TARGET }}node && npm install && cd .. && cd ./laravel && composer install 
      - run: echo "🍏 This job's status is ${{ job.status }}."